AUTHURL = 'http://127.0.0.1:5000/v2.0'
USER = 'enctesta'
KEY = 'enctesta!'
TENANT_NAME = 'meta_encswift'
ADMIN_USER = 'encadmin'
ADMIN_KEY = 'encadmin!'
META_TENANT = 'meta'
META_TENANT_SEL = 'meta_sel'
